// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_end.Models.cpp_tute", b =>
                {
                    b.Property<Guid>("topic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("topic_id");

                    b.ToTable("cpp_tute");
                });

            modelBuilder.Entity("back_end.Models.cs_tute", b =>
                {
                    b.Property<Guid>("topic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("topic_id");

                    b.ToTable("cs_tute");
                });

            modelBuilder.Entity("back_end.Models.javascript_tute", b =>
                {
                    b.Property<Guid>("topic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sort_key")
                        .HasColumnType("int");

                    b.Property<string>("topic_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("topic_id");

                    b.ToTable("javascript_tute");
                });

            modelBuilder.Entity("back_end.Models.python_tute", b =>
                {
                    b.Property<Guid>("topic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("topic_id");

                    b.ToTable("python_tute");
                });
#pragma warning restore 612, 618
        }
    }
}
